name: Continous Delivery

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build, publish to GPR and tag
        run: |
          set -e
          revisionMajor=0
          revisionMinor=1
          revisionPatch=$GITHUB_RUN_NUMBER
          version="$revisionMajor.$revisionMinor.$revisionPatch"
          commit=$(git rev-parse HEAD)
          remote=$(git config --get remote.origin.url)
          repo=$(basename $remote .git)
          echo "Building $version at $commit"
          mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision.major=$revisionMajor -Drevision.minor=$revisionMinor -Drevision.patch=$revisionPatch
          ref="refs/tags/$version"
          url="https://api.github.com/repos/$GITHUB_REPOSITORY/git/ref"
          echo "Tagging $ref to $url"
          curl -s -X POST $url -H "Authorization: token $GITHUB_TOKEN" -d @- << EOF
          {
            "ref": "$ref",
            "sha": "$commit"
          }
          EOF
        env:
          GITHUB_TOKEN: ${{ github.token }}