name: Continous Delivery

on:
  push:
    branches: [master]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build, publish to GPR and tag
        run: |
          if [ "$GITHUB_REPOSITORY" == "gruelbox/transaction-outbox" ]; then
            revision="1.3.$GITHUB_RUN_NUMBER"
            echo "Building $revision at $GITHUB_SHA"
            mvn -Pdelombok -B deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision="$revision"
            echo "Tagging $revision"
            git tag $revision
            git push origin $revision

            echo "Updating READMEs - temporary for testing"
            sed -i "s_\(<version>\)[^<]*_\1${revision}_g" README.md
            sed -i "s_\(<version>\)[^<]*_\1${revision}_g" transactionoutbox-guice/README.md
            sed -i "s_\(<version>\)[^<]*_\1${revision}_g" transactionoutbox-jooq/README.md
            sed -i "s_\(<version>\)[^<]*_\1${revision}_g" transactionoutbox-spring/README.md
            sed -i "s_\(implementation 'com.gruelbox:transactionoutbox-core:\)[^']*_\1${revision}_g" README.md
            sed -i "s_\(implementation 'com.gruelbox:transactionoutbox-guice:\)[^']*_\1${revision}_g" transactionoutbox-guice/README.md
            sed -i "s_\(implementation 'com.gruelbox:transactionoutbox-jooq:\)[^']*_\1${revision}_g" transactionoutbox-jooq/README.md
            sed -i "s_\(implementation 'com.gruelbox:transactionoutbox-spring:\)[^']*_\1${revision}_g" transactionoutbox-spring/README.md
          else
            mvn -Pdelombok -B package
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "Update versions in READMEs [skip ci]"
          title: Update versions in READMEs
          body: Updates the versions in the README files following the release
          branch: update-readme-versions
