name: R2DBC support branch

on:
  push:
    branches: [r2dbc4]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ~ # location for the settings.xml file

      - name: Set up testcontainers reuse
        run: |
          echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties

      - name: Build, publish snapshot to OSSRH
        run: |
          if [ "$GITHUB_REPOSITORY" == "gruelbox/transaction-outbox" ]; then
            revision="2.1.13-SNAPSHOT"
            mvn -Prelease,delombok -B test -s -Drevision=$revision
          else
            mvn -Pdelombok -B package
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_EXECUTABLE: gpg
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
