name: Pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  format-and-delombok:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-package: jdk
          java-version: 21
          cache: 'maven'
      - name: Build with Maven
        run: mvn -Pconcise,delombok -B fmt:check package -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs-core
          path: transactionoutbox-core/target/apidocs
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs-guice
          path: transactionoutbox-guice/target/apidocs
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs-jackson
          path: transactionoutbox-jackson/target/apidocs
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs-jooq
          path: transactionoutbox-jooq/target/apidocs
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs-quarkus
          path: transactionoutbox-quarkus/target/apidocs
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs-spring
          path: transactionoutbox-spring/target/
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 11,17,21 ]
        db: [ nodb,mysql,postgres,oracle ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-package: jdk
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -Pconcise,only-${{ matrix.db }}-tests -B package -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn