name: Pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [11,17,20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Set up testcontainers reuse
        run: |
          echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties

      - name: Build with Maven
        run: mvn -Pconcise -B package -fae -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/target/surefire-reports/**/*.xml