name: Continous Delivery

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build and publish
        run: |
          version=( ${GITHUB_REF//./ } )
          echo "Publishing version ${version[0]}.${version[1]}.${version[2]}"
          echo ${{ GPG_SECRET_KEYS }} | base64 --decode | $GPG_EXECUTABLE --import
          echo ${{ GPG_OWNERTRUST }} | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
          mvn -Prelease -B deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision.major=${version[0]} -Drevision.minor=${version[1]} -Drevision.patch=${version[2]}-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONATYPE_USERNAME: ${{ SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ SONATYPE_PASSWORD }}
          GPG_EXECUTABLE: gpg
          GPG_KEYNAME: ${{ GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ GPG_PASSPHRASE }}